### ISSUE TITLE
Assignment #1 Transfer Functions are wrong

### ISSUE THREAD

**Issue by rxa254** [rxa254/ph237#10]
the part 1 of the FP transfer function was giving nonsensical results since the length was wrong

- the cavity has to be tuned to be an integer # of wavelengths to make it resonate
- it then has to be shifted off resonance by a small amount so that there is a linear response; otherwise the transmitted power is quadratic in the mirror motion (somehow didn't realize that one for awhile !)

Would be good if you can take a look at this and perhaps transfer some of your Latex into this notebook (when you get some free time) so that its self-contained. We can explain the corrected solution in class on Tuesday.

** when saving/committing .ipynb files its good practice to 'Clear All Output'. This then removes the graphics so that we're only committing the text file - allows for easier diff operations probably,.

**Comment by zmarkcaltech** [comment]
Thank you for going through this notebook and diagnosing the issue. I'm sorry for the late response (Kevin and I were working on Hypothesis testing on the nice blackboard in bridge!)

Also there was some confusion over the correct definition of the transfer function. Given that you didn't modify my definition, I will assume that my definition was correct (i.e. there was not actually any confusion).

It sounds like you would prefer explanation directly in the ipython notebook over the separate solution set. I will do this (and figure out how to do this) tomorrow so we can share the results with the class on Tuesday.

**Comment by rxa254** [comment]
I think it's one of the nice features of ipython notebooks. You can put
Latex for commenting like in Mathematica, but with 'Markdown' syntax.

**Comment by zmarkcaltech** [comment]
Hi Rana,

I updated the ipython notebook with the writing from my latex solution. Namely, every problem is now solved in the ipython notebook so we don't really even have to distribute the other solution anymore.

Best,

Zach
