### ISSUE TITLE
Assignment #5: Echoes

### ISSUE THREAD

**Issue by rxa254** [rxa254/ph237#12]
ipython notebook with some rough problem ideas

**Comment by zmarkcaltech** [comment]
I don't see the ipython notebook...

**Comment by rxa254** [comment]
yes, exactly - "rough problem ideas" needed; please add

**Comment by alurban** [comment]
hint taken! sorry I disappeared, I just got back from Baton Rouge - I'll have something to you soon.

@rxa254 did you get the notebook I emailed around? I didn't post it to github because it has full solutions.
